version: "3.5"

networks:
  default:
    attachable: true
    name: "traefik"

services:
  traefik:
    image: "traefik:v3.1"
    command: --providers.docker
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./acme.json:/acme.json"
      - "./config:/config"

  neko-rooms:
    image: "m1k1o/neko:firefox"
    restart: "unless-stopped"
    shm_size: "8gb"
    env_file:
      - ".env"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.neko-frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.neko.rule=Host(`serienabend.duckdns.org`)"
      - "traefik.http.routers.neko.entrypoints=websecure"
      - "traefik.http.routers.neko.tls.certresolver=lets-encrypt"
