services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 30s
      timeout: 3s

  rallly:
    image: lukevella/rallly:latest
    restart: unless-stopped
    # ports:
    #   - 3000:3000
    env_file:
      - rallly.env

  invidious:
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./invidious:/config
    environment:
      - INVIDIOUS_CONFIG_FILE=config/invidious.yml
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "100M"
        max-file: "4"

  stirling-pdf:
    image: frooodle/s-pdf:latest-ultra-lite
    restart: unless-stopped
    # ports:
    #   - '8080:8080'
    volumes:
      - ./pdf/trainingData:/usr/share/tessdata
      - ./pdf/extraConfigs:/configs
    env_file:
      - stirling.env

  miniflux:
    image: miniflux/miniflux:latest
    restart: unless-stopped
    # ports:
    #   - "8080:8080"
    env_file:
      - miniflux.env

  it-tools:
    image: corentinth/it-tools:latest
    restart: unless-stopped
    # ports:
    #   - 80:80

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    volumes:
      - ./pgadmin:/pgadmin4/servers.json
    # ports:
    #   - "80:80"
    env_file:
      - pgadmin.env

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - watchtower.env

networks:
  default:
    external: true
    name: net
